apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auth-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/walabelhi/microapp
    targetRevision: main
    path: charts/auth-service

  destination:
    server: https://kubernetes.default.svc
    namespace: auth

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
