apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/walabelhi/micro-app
    targetRevision: main
    path: client/k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: client
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
