apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tickets-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/walabelhi/micro-app
    targetRevision: main
    path: tickets/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: tickets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
